spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Achamanp/microservice-config
          clone-on-start: true
          default-label: main  # Specify the branch explicitly
          timeout: 10  # Connection timeout in seconds
          
server:
  port: 8585